apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: liferay-default
  namespace: liferay-able-dev
spec:
  ingressClassName: nginx
  rules:
  - host: liferay-able-dev.runray.xyz
    http:
      paths:
      - backend:
          service:
            name: liferay-default
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - liferay-able-dev.runray.xyz
    secretName: runray.xyz-tls