apiVersion: v1
kind: ConfigMap
metadata:
  name: customrestservice-dxp-configs
  labels:
    cloud.liferay.com/serviceId: customrestservice
    dxp.liferay.com/configs: "true"
  annotations:
    cloud.liferay.com/context-data: '{"domains":["customrestservice.localdev.me"]}'
data:
  default: "empty"