v1alpha1.extension_repo(name='default', url='https://github.com/gamerson/tilt-extensions')
load('ext://lxc', 'lxc_extension_helm')

k8s_yaml(
  helm(
    '../kubernetes-native-dxp/charts/dxp-localdev',
    name='dxp-localdev',
    values=['./values-dxp-localdev.yaml'],
  )
)

lxc_extension_helm(
  name='designpackfire',
  command='cd ./extensions/designpackfire && gradle build && docker build -t $EXPECTED_REF .',
  deps=[
    './extensions/designpackfire/src',
    'package.json'
  ],
  ignore=[
    './extensions/designpackfire/build', 
    './extensions/designpackfire/dist'
  ],
  chart_path='../kubernetes-native-dxp/charts/static-localdev',
  values=['./extensions/designpackfire/values.yaml']
)

#lxc_extension(
#  name='dynamicjscss',
#  command='cd ./extensions/dynamicjscss && docker build -t $EXPECTED_REF .',
#  deps=['./extensions/dynamicjscss/src'],
#  ignore=[],
#  chart_path='../kubernetes-native-dxp/charts/static-localdev',
#  values=['./extensions/dynamicjscss/values.yaml']
#)