apply plugin: "com.liferay.poshi.runner"

task liferayIsReady

afterEvaluate {
	runPoshi {
		dependsOn ":startDockerContainer", liferayIsReady
		finalizedBy ":stopDockerContainer"
	}
}

dependencies {
	poshiRunnerResources group: "com.liferay", name: "com.liferay.poshi.runner.resources", version: "latest.release"
}

liferayIsReady {
	doLast {
		def portalUrl = "http://localhost:8080"
		def max = 50
		def sleep = 5000
		def responseCode = -1

		def attempts = 0
		while (attempts < max) {
			try {
				responseCode = portalUrl.toURL().openConnection().responseCode
				if (responseCode == 200) {
					println("Portal is up!")
					break
				}
			}
			catch (Throwable t) {
			}
			attempts++
			println("Try #$attempts failed. Response code is $responseCode. Sleeping...")
			try {
				Thread.sleep(sleep)
			}
			catch (InterruptedException ie) {
			}
		}
	}
}

poshiRunner {
	poshiPropertiesFile = file("poshi.properties")
}

repositories {
	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}