apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-oidc-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "GOOGLE_OIDC_CLIENT_ID" "GOOGLE_OIDC_CLIENT_SECRET" }}
  {{ . }}: {{ $files.Get . }}
  {{- end }}