---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cne-licensing-agent-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - licensing.liferay.com
  resources:
  - liferayenvironments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - licensing.liferay.com
  resources:
  - liferayenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - licensing.liferay.com
  resources:
  - liferayenvironments/status
  verbs:
  - get
  - patch
  - update
