dependencies {
	compileOnly project(":portal-kernel")
	compileOnly group: "commons-validator", name: "commons-validator", version: "1.5.0"
	compileOnly group: "javax.mail", name: "mail", version: "1.4"
	compileOnly project(":modules:core:petra:petra-string")

	testCompile project(":modules:core:petra:petra-lang")
}