#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    external-liferay,\
    liferay-sample-etc-external-oauth-client
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081