task runGradleTest

dependencies {
	providedModules group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.10.3"
	providedModules group: "com.google.guava", name: "guava"
}

runGradleTest {
	dependsOn initBundle

	doLast {
		File googleGuavaFile = new File(initBundle.destinationDir, "osgi/modules/guava-16.0.1.jar")
		File jacksonAnnotationsFile = new File(initBundle.destinationDir, "osgi/modules/jackson-annotations-2.10.3.jar")

		assert googleGuavaFile.exists()
		assert jacksonAnnotationsFile.exists()
	}
}