apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamicjscss-dxp-configs
  labels:
    cloud.liferay.com/serviceId: dynamicjscss
    dxp.liferay.com/configs: "true"
  annotations:
    cloud.liferay.com/context-data: '{"domains":["dynamicjscss.localdev.me"]}'
data:
  default: "empty"