#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
  liferay-sample-etc-external-threads-count,\
  external-liferay-oauth-headless-server,\
  external-liferay-oauth-user-agent
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081