com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http
liferay.oauth.application.external.reference.code=liferay-sample-oauth-application-headless-server
liferay-sample-oauth-application-headless-server.oauth2.headless.server.client.secret=<secret>
liferay-sample-oauth-application-headless-server.oauth2.token.uri=/o/oauth2/token