com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http
logging.level.com.sample=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
liferay.oauth.application.external.reference.code=sample-oauth-application-user-agent
server.port=58081