# add this on first line so it is loaded first
spring.config.import=configtree:/etc/liferay/lxc/*/

com.liferay.lxc.dxp.domains=localhost:8080
logging.level.com.liferay.sample.minimal.workspace.joke=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
lxc.default.oauth.application=joke-oauth-application-user-agent
server.port=80