apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ include "liferayAWSExtensions.name" . }}
spec:
    accessModes:
        -   ReadWriteMany
    capacity:
        storage: 1Gi
    claimRef:
        name: {{ include "liferayAWSExtensions.name" . }}
        namespace: {{ .Release.Namespace }}
    csi:
        driver: s3.csi.aws.com
        volumeAttributes:
            bucketName: {{ .Values.bucketName }}
        volumeHandle: {{ .Values.bucketName }}
    storageClassName: {{ .Values.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "liferayAWSExtensions.name" . }}
spec:
    accessModes:
        -   ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    storageClassName: {{ .Values.storageClassName }}