//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientExtension) DeepCopyInto(out *ClientExtension) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientExtension.
func (in *ClientExtension) DeepCopy() *ClientExtension {
	if in == nil {
		return nil
	}
	out := new(ClientExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientExtension) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientExtensionList) DeepCopyInto(out *ClientExtensionList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	out.TypeMeta = in.TypeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientExtensionList.
func (in *ClientExtensionList) DeepCopy() *ClientExtensionList {
	if in == nil {
		return nil
	}
	out := new(ClientExtensionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientExtensionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientExtensionSpec) DeepCopyInto(out *ClientExtensionSpec) {
	*out = *in
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.LiferayEnvironmentRef = in.LiferayEnvironmentRef
	if in.WorkloadRef != nil {
		in, out := &in.WorkloadRef, &out.WorkloadRef
		*out = new(WorkloadRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientExtensionSpec.
func (in *ClientExtensionSpec) DeepCopy() *ClientExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(ClientExtensionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientExtensionStatus) DeepCopyInto(out *ClientExtensionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedConfigurationPIDs != nil {
		in, out := &in.AppliedConfigurationPIDs, &out.AppliedConfigurationPIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigurationErrors != nil {
		in, out := &in.ConfigurationErrors, &out.ConfigurationErrors
		*out = make([]ConfigurationError, len(*in))
		copy(*out, *in)
	}
	if in.ExtProvisionConfigMapNames != nil {
		in, out := &in.ExtProvisionConfigMapNames, &out.ExtProvisionConfigMapNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadIssues != nil {
		in, out := &in.WorkloadIssues, &out.WorkloadIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientExtensionStatus.
func (in *ClientExtensionStatus) DeepCopy() *ClientExtensionStatus {
	if in == nil {
		return nil
	}
	out := new(ClientExtensionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationError) DeepCopyInto(out *ConfigurationError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationError.
func (in *ConfigurationError) DeepCopy() *ConfigurationError {
	if in == nil {
		return nil
	}
	out := new(ConfigurationError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiferayEnvironmentRef) DeepCopyInto(out *LiferayEnvironmentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiferayEnvironmentRef.
func (in *LiferayEnvironmentRef) DeepCopy() *LiferayEnvironmentRef {
	if in == nil {
		return nil
	}
	out := new(LiferayEnvironmentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
