##
## Check GETTING_STARTED.markdown for additional properties and their default
## values.
##

# for testing against liferay/liferay-portal
liferay.workspace.home.dir=/home/me/projects/bundles

liferay.workspace.bundle.dist.include.metadata=true
liferay.workspace.modules.dir=modules
liferay.workspace.node.package.manager=yarn
liferay.workspace.product=dxp-2023.q4.5
liferay.workspace.themes.dir=themes

##
## To target a non-default virtual instance in liferay set this property to
## the web id of the virtual instance
##
#liferay.workspace.virtual.instance.id=vi.one.private

liferay.workspace.wars.dir=modules
microsoft.translator.subscription.key=