FROM golang:1.24 AS builder

WORKDIR /workspace

COPY resources resources

RUN cd resources && CGO_ENABLED=0 GOOS=linux go build -o /dxpsim ./cmd/dxpsim

FROM gcr.io/distroless/static:nonroot

ENTRYPOINT ["/dxpsim"]

COPY --from=builder /dxpsim /dxpsim

USER 65532:65532
