apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb
    namespace: __LIFERAY_NAMESPACE__
spec:
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mariadb
    namespace: __LIFERAY_NAMESPACE__
spec:
    ports:
        -   port: 3306
            targetPort: 3306
    selector:
        app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mariadb
    namespace: __LIFERAY_NAMESPACE__
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mariadb
    template:
        metadata:
            labels:
                app: mariadb
        spec:
            containers:
                -   args:
                        -   --character-set-server=utf8mb4
                        -   --collation-server=utf8mb4_unicode_ci
                        -   --max-allowed-packet=256M
                    env:
                        -   name: MARIADB_DATABASE
                            value: lportal
                        -   name: MARIADB_PASSWORD
                            value: liferay
                        -   name: MARIADB_ROOT_PASSWORD
                            value: liferay
                        -   name: MARIADB_USER
                            value: liferay
                    image: __MARIADB_IMAGE__
                    name: mariadb
                    ports:
                        -   containerPort: 3306
                    readinessProbe:
                        exec:
                            command:
                                -   healthcheck.sh
                                -   --connect
                        initialDelaySeconds: 10
                        periodSeconds: 5
                    resources:
                        limits:
                            cpu: "1"
                            memory: 1Gi
                        requests:
                            cpu: 100m
                            memory: 256Mi
                    volumeMounts:
                        -   mountPath: /var/lib/mysql
                            name: data
            volumes:
                -   name: data
                    persistentVolumeClaim:
                        claimName: mariadb