defaults:
    run:
        shell: bash
jobs:
    publish-liferay-aws-bootstrap:
        if: ${{github.repository == 'gamerson/liferay-portal'}}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Authenticate to Google Cloud
                uses: 'google-github-actions/auth@v2'
                with:
                    service_account: '${GCP_GITHUB_ACTIONS_UPLOADER_SA}'
                    workload_identity_provider: 'projects/${GCP_PROJECT_ID}/locations/global/workloadIdentityPools/${GCP_WORKLOAD_IDENTITY_POOL_NAME}/providers/${GCP_GITHUB_PROVIDER_NAME}'
            -   name: Set up gcloud CLI
                uses: 'google-github-actions/setup-gcloud@v2'
                with:
                    project_id: '${GCP_PROJECT_NAME}'
            -   id: verify_version
                name: Verify version
                run: |
                    CURRENT_VERSION=$(jq -r '."liferay-aws-bootstrap"' ./scripts/versions.json)
                    GCS_BUCKET_NAME="liferay-cloud-native-bootstrap-nonprd"
                    PACKAGE_NAME="liferay-aws-bootstrap"
                    GCS_PATH="gs://${GCS_BUCKET_NAME}/${PACKAGE_NAME}/${PACKAGE_NAME}-${CURRENT_VERSION}.tar.gz"

                    if ! gsutil --quiet ${GCS_PATH}
                    then
                        echo "Verified version ${CURRENT_VERSION}."

                        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> ${GITHUB_ENV}

                        echo "should_publish=true" >> ${GITHUB_OUTPUT}
                    else
                        echo "Version ${CURRENT_VERSION} already exists. Skipping publish."
                    fi
                working-directory: ./cloud
            -   if: ${{steps.verify_version.outputs.should_publish == 'true'}}
                name: Package and push AWS bootstrap scripts
                run: |
                    OUTPUT_FILENAME="liferay-aws-bootstrap-${CURRENT_VERSION}.tar.gz"
                    OUTPUT_LOCATION="/tmp/${OUTPUT_FILENAME}"

                    tar \
                        --create \
                        --file ${OUTPUT_LOCATION} \
                        --gzip \
                        --verbose \
                        ./terraform/aws/eks/*.tf \
                        ./terraform/aws/gitops/platform/*.tf \
                        ./terraform/aws/gitops/resources/*.tf

                    GCS_BUCKET_NAME="liferay-cloud-native-bootstrap-nonprd"
                    PACKAGE_NAME="liferay-aws-bootstrap"
                    GCS_DEST_PATH="gs://${GCS_BUCKET_NAME}/${PACKAGE_NAME}/${PACKAGE_NAME}-${CURRENT_VERSION}.tar.gz"

                    gcloud storage cp \
                        ${OUTPUT_LOCATION} \
                        ${GCS_DEST_PATH}
                working-directory: ./cloud
on:
    push:
        branches:
            -   LCD-49898-gcs-test
        paths:
            -   .github/workflows/ci-publish-cloud-scripts.yaml
            -   cloud/scripts/versions.json
            -   cloud/terraform/aws/eks/*
            -   cloud/terraform/aws/gitops/platform/*
            -   cloud/terraform/aws/gitops/resources/*
permissions:
    id-token: write