dependencies {
	compileOnly project(":modules:core:petra:petra-memory")

	testCompile project(":portal-kernel")
	testCompile project(":modules:core:petra:petra-lang")
	testCompile project(":modules:core:petra:petra-reflect")
	testCompile project(":modules:core:petra:petra-string")
}

liferay {
	deployDir = appServerLibGlobalDir
}